"""add memory tables

Revision ID: 001_add_memory_tables
Revises: 
Create Date: 2026-04-22 00:55:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '001_add_memory_tables'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_items',
    sa.Column('id', sa.String(length=64), nullable=False, comment='记忆项ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='记忆内容'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='记忆分类'),
    sa.Column('tags', sa.Text(), nullable=True, comment='标签列表(JSON格式)'),
    sa.Column('importance', sa.Integer(), nullable=False, comment='重要性等级(1-10)'),
    sa.Column('relevance_score', sa.Float(), nullable=True, comment='相关性分数'),
    sa.Column('metadata', sa.Text(), nullable=True, comment='元数据(JSON格式)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('session_id', sa.String(length=64), nullable=False, comment='会话ID'),
    sa.Column('agent_id', sa.String(length=64), nullable=True, comment='关联的Agent ID'),
    sa.Column('context', sa.Text(), nullable=True, comment='会话上下文(JSON格式)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memory_sessions')
    op.drop_table('memory_items')
    # ### end Alembic commands ###